export const USER_REQUESTED = "USER_REQUESTED";
export const USER_LOADED = "USER_LOADED";
export const USER_DELETED = "USER_DELETED";

export const AUTH_ERROR = "AUTH_ERROR";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";
export const DEACTIVATION_SUCCESS = "DEACTIVATION_SUCCESS";
export const DEACTIVATION_FAILED = "DEACTIVATION_FAILED";

export const ERRORS_RETURNED = "ERRORS_RETURNED";
export const ERRORS_LOGGED = "ERRORS_LOGGED";
export const LOGGING_ERROR = "LOGGING_ERRORs";
export const ERRORS_CLEARED = "ERRORS_CLEARED";

export const SONGS_REQUESTED = "SONGS_REQUESTED";
export const SONGS_ERROR = "SONGS_ERROR";
export const SONGS_FETCHED = "SONGS_FETCHED";

export const PAYMENTS_REQUESTED = "PAYMENTS_REQUESTED";
export const PAYMENTS_ERROR = "PAYMENTS_ERROR";
export const STRIPE_SUBSCRIPTION_CREATED = "STRIPE_SUBSCRIPTION_CREATED";
export const STRIPE_PUBLIC_KEY_FETCHED = "STRIPE_PUBLIC_KEY_FETCHED";
export const STRIPE_SUBSCRIPTION_DELETED = "STRIPE_SUBSCRIPTION_DELETED";
export const PAYPAL_SUBSCRIPTION_CREATED = "PAYPAL_SUBSCRIPTION_CREATED";
export const PAYPAL_SUBSCRIPTION_DELETED = "PAYPAL_SUBSCRIPTION_DELETED";

